---
- hosts: "{{ server }}"
  tasks:
  - name: Checking current version
    shell: tail -2 /root/builds/builds.list | head -1 | awk -F. '{print $1 $2}'
    register: current_version
  - debug:
      msg: "{{ current_version.stdout }}"
  - name: Checking upgrade version
    shell: echo "{{ proposed_version }}" | awk -F. '{print $1 $2}'
    register: upgrade_version
  - debug:
      msg: "{{ upgrade_version.stdout }}"
    failed_when: upgrade_version.stdout|int != current_version.stdout|int
